### PR TITLE
Bluetooth doesn't kill itself anymore when scanning

### PR DESCRIPTION
**Pull request by averycblack**

### CODE REVIEW

**Review by rv32ima — APPROVED** [review]
Looks good to me, pretty trivial change

**Comment by lvs1974** [comment]
@hatf0, @1Revenger1: could anybody suggest a stable bluetooth kext for Wireless-AC 9560, please?
I tried https://github.com/zxystd/IntelBluetoothFirmware (the latest release) and bluetooth did not work at all.
Thank you in advance!

**Comment by tctien342** [comment]
@lvs1974 mine 9560 is work perfectly with that kext, expect mouse

**Comment by averycblack** [comment]
I use that kext as well, but I've found it has issues when going out of sleep sometimes. It also likes to give me panics when coming out of sleep related to USB. I haven't really looked around much tbh. @lvs1974

**Comment by lvs1974** [comment]
> @lvs1974 mine 9560 is work perfectly with that kext, expect mouse

Do you mean the latest release, version 1.0.3?
I tried to load these injector and firmware kexts with OC without any luck - there is no bluetooth.
After I put these two kexts into /Library/Extensions, fixed owner, permissions and rebuilt a kernel cache - there is no bluetooth.

Previous version sometimes showed bluetooth and I could even connect some devices, but when I tried to use them (for example bluetooth headset) - no luck again.

**Comment by williambj1** [comment]
@lvs1974 

The kext works for me, macOS Catalina, but it only serves as a firmware uploader, I get the same result from directly rebooting from Windows. After the firmware is uploaded, Bluetooth runs under a lot of incompatible Broadcom kexts, Bluetooth 4.0 is not usable e.g. I can't connect my keyboard but Bluetooth 5.0 seems to work fine (Air Pods, etc.) 

EDIT: I'm currently using 1.0.2 injecting the two kexts with OpenCore (clover works fine as well),  maybe give the old version a try?

**Comment by tctien342** [comment]
@lvs1974 yep, last one, boot may slower
+ Tested keychron k2 keyboard, ES100 bluetooth DAC, Samsung soundbar working correctly without any delay
+ Failled on all bluetooth mouse, cant connect to it

> Mine card
91911958_244653706664945_6323072276468072448_n

**Comment by rv32ima** [comment]
@lvs1974 Bluetooth **HEAVILY** relies on the WiFi card being initialized. If it doesn't work, and your Bluetooth isn't showing up, it's due to the wireless card being uninitialized. When (and this is a case of when) this kext is actually stable, you'll notice that bluetooth starts to work 100%. That's just a simple case of us powering on the device, really.

**Comment by averycblack** [comment]
Last one I tried was 1.0.2.
My OnePlus 7T connects fine for bluetooth internet, and my Magic Trackpad 2 connects just fine.

I've noticed a bit more stabilty when using this kext as is, though I haven't really done much testing to prove that it is more stable.

**Comment by williambj1** [comment]
@hatf0 I believe your theory is absolutely correct but how could this explain why I could use Bluetooth without "powering" (do you mean powering by "adapter")?

**Comment by rv32ima** [comment]
@williambj1 I’m fairly certain that Windows doesn’t bother shutting down the device when it shuts down. If you ever reboot from Windows into Linux, you’ll notice a message in the kernel log (“device was already configured”). This would also explain why Bluetooth works, but stops working after a cold reboot.

**Comment by lvs1974** [comment]
Thanks to everybody, after boot into Windows and warm restart into macOS IntelBluetoothFirmware 1.0.3 works.

**Comment by pytason** [comment]
Warm reboot from windows should work without the kexts anyways. As stated before windows loads the bluetooth firmware and since windows doesnt shut it down. the firmware will be available in macos.

So you are still using the firmware loaded by windows (not by the kexts)

**Comment by rv32ima** [comment]
@pytason Indeed, it does, and you are using the firmware loaded by Windows. It seems that (like the rest of Intel devices), it retains it's state across warm reboots. It's best (imho) to use the IntelBluetoothFirmware loader, though, as it'll probably play a massive role in the coming future.

**Comment by lvs1974** [comment]
It is a bit more difficult. After warm restart (from Windows) and booting into macOS Bluetooth worked, and it worked after a few sleep/wake cycles. Then I restarted and boot into macOS again. There was no Bluetooth.
I put laptop into sleep and awoke it. Bluetooth works!

**Comment by mehmetyukcell** [comment]
> @lvs1974 mine 9560 is work perfectly with that kext, expect mouse

How do you do?

**Pull request merged**
