### PR TITLE
9000 Series Support

### PR DESCRIPTION
**Pull request by averycblack**
Shows scan results under the wireless diagnostic menu though not in the wifi drop-down.

### CODE REVIEW

**Comment by tctien342** [comment]
+ Comfirmed scan work with mine ngw9560
Screen Shot 2020-04-02 at 13 16 39

**Comment by lvs1974** [comment]
@tctien342, @1Revenger1: strange, but kext build from this branch did not work for me.
"Microcode SW error detected.  Restarting 0x2000000." is still in place.
[log.txt](https://github.com/AppleIntelWifi/adapter/files/4419642/log.txt)

**Comment by averycblack** [comment]
I'm noticing that an LTR command is being sent at config time, which doesn't get sent on my 9560 @lvs1974 
What happens if you set this if statement to be always false so that the command never gets sent? 
https://github.com/1Revenger1/adapter/blob/master/AppleIntelWifiAdapter/mvm/IWLMvmDriver.cpp#L583

**Comment by lvs1974** [comment]
@1Revenger1: I commented out lines 583-590 and rebuilt kext.  It seems it did not help.
Anyway, thank you for the idea. 
[log.txt](https://github.com/AppleIntelWifi/adapter/files/4423222/log.txt)

**Comment by averycblack** [comment]
@lvs1974 The command still got sent. You might want to check what kext your loading...
image

**Comment by Timothybas** [comment]
@1Revenger1 I tried as you said still device not listing.
[log.txt](https://github.com/AppleIntelWifi/adapter/files/4423295/log.txt)

**Comment by lvs1974** [comment]
@1Revenger1, you are right, here is the right log with right kext:
[log.txt](https://github.com/AppleIntelWifi/adapter/files/4423333/log.txt)

**Comment by averycblack** [comment]
@lvs1974 looks like it's finding networks now. Looks good.
@Timothybas let me look further into that, looks like it fails to initialize after loading up the firmware.

**Comment by averycblack** [comment]
Oops, meant to add this.
Thanks you all for testing this

**Comment by mehmetyukcell** [comment]
Where support 9560ac?

**Comment by rv32ima** [comment]
@1Revenger1 can you squash your commits down? otherwise, LGTM

**Comment by lvs1974** [comment]
@1Revenger1, thank you for the hard work!

**Pull request merged**
